/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Event enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Event {
    MessageEvent(Box<models::MessageEvent>),
    UnsendEvent(Box<models::UnsendEvent>),
    FollowEvent(Box<models::FollowEvent>),
    UnfollowEvent(Box<models::UnfollowEvent>),
    JoinEvent(Box<models::JoinEvent>),
    LeaveEvent(Box<models::LeaveEvent>),
    MemberJoinedEvent(Box<models::MemberJoinedEvent>),
    MemberLeftEvent(Box<models::MemberLeftEvent>),
    PostbackEvent(Box<models::PostbackEvent>),
    VideoPlayCompleteEvent(Box<models::VideoPlayCompleteEvent>),
    BeaconEvent(Box<models::BeaconEvent>),
    AccountLinkEvent(Box<models::AccountLinkEvent>),
    MembershipEvent(Box<models::MembershipEvent>),
    ModuleEvent(Box<models::ModuleEvent>),
    ActivatedEvent(Box<models::ActivatedEvent>),
    DeactivatedEvent(Box<models::DeactivatedEvent>),
    BotSuspendedEvent(Box<models::BotSuspendedEvent>),
    BotResumedEvent(Box<models::BotResumedEvent>),
    PnpDeliveryCompletionEvent(Box<models::PnpDeliveryCompletionEvent>),
}

impl Default for Event {
    fn default() -> Self {
        Self::MessageEvent(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::MessageEvent> for Event {
    fn from(value: models::MessageEvent) -> Self {
        Event::MessageEvent(Box::new(value))
    }
}

impl From<models::UnsendEvent> for Event {
    fn from(value: models::UnsendEvent) -> Self {
        Event::UnsendEvent(Box::new(value))
    }
}

impl From<models::FollowEvent> for Event {
    fn from(value: models::FollowEvent) -> Self {
        Event::FollowEvent(Box::new(value))
    }
}

impl From<models::UnfollowEvent> for Event {
    fn from(value: models::UnfollowEvent) -> Self {
        Event::UnfollowEvent(Box::new(value))
    }
}

impl From<models::JoinEvent> for Event {
    fn from(value: models::JoinEvent) -> Self {
        Event::JoinEvent(Box::new(value))
    }
}

impl From<models::LeaveEvent> for Event {
    fn from(value: models::LeaveEvent) -> Self {
        Event::LeaveEvent(Box::new(value))
    }
}

impl From<models::MemberJoinedEvent> for Event {
    fn from(value: models::MemberJoinedEvent) -> Self {
        Event::MemberJoinedEvent(Box::new(value))
    }
}

impl From<models::MemberLeftEvent> for Event {
    fn from(value: models::MemberLeftEvent) -> Self {
        Event::MemberLeftEvent(Box::new(value))
    }
}

impl From<models::PostbackEvent> for Event {
    fn from(value: models::PostbackEvent) -> Self {
        Event::PostbackEvent(Box::new(value))
    }
}

impl From<models::VideoPlayCompleteEvent> for Event {
    fn from(value: models::VideoPlayCompleteEvent) -> Self {
        Event::VideoPlayCompleteEvent(Box::new(value))
    }
}

impl From<models::BeaconEvent> for Event {
    fn from(value: models::BeaconEvent) -> Self {
        Event::BeaconEvent(Box::new(value))
    }
}

impl From<models::AccountLinkEvent> for Event {
    fn from(value: models::AccountLinkEvent) -> Self {
        Event::AccountLinkEvent(Box::new(value))
    }
}

impl From<models::MembershipEvent> for Event {
    fn from(value: models::MembershipEvent) -> Self {
        Event::MembershipEvent(Box::new(value))
    }
}

impl From<models::ModuleEvent> for Event {
    fn from(value: models::ModuleEvent) -> Self {
        Event::ModuleEvent(Box::new(value))
    }
}

impl From<models::ActivatedEvent> for Event {
    fn from(value: models::ActivatedEvent) -> Self {
        Event::ActivatedEvent(Box::new(value))
    }
}

impl From<models::DeactivatedEvent> for Event {
    fn from(value: models::DeactivatedEvent) -> Self {
        Event::DeactivatedEvent(Box::new(value))
    }
}

impl From<models::BotSuspendedEvent> for Event {
    fn from(value: models::BotSuspendedEvent) -> Self {
        Event::BotSuspendedEvent(Box::new(value))
    }
}

impl From<models::BotResumedEvent> for Event {
    fn from(value: models::BotResumedEvent) -> Self {
        Event::BotResumedEvent(Box::new(value))
    }
}

impl From<models::PnpDeliveryCompletionEvent> for Event {
    fn from(value: models::PnpDeliveryCompletionEvent) -> Self {
        Event::PnpDeliveryCompletionEvent(Box::new(value))
    }
}
