/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Event enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Event {
    #[serde(rename = "message")]
    MessageEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken", skip_serializing_if = "Option::is_none")]
        reply_token: Option<String>,
        #[serde(rename = "message")]
        message: Box<models::MessageContent>,
    },
    #[serde(rename = "unsend")]
    UnsendEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "unsend")]
        unsend: Box<models::UnsendDetail>,
    },
    #[serde(rename = "follow")]
    FollowEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken")]
        reply_token: String,
        #[serde(rename = "follow")]
        follow: Box<models::FollowDetail>,
    },
    #[serde(rename = "unfollow")]
    UnfollowEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
    },
    #[serde(rename = "join")]
    JoinEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken")]
        reply_token: String,
    },
    #[serde(rename = "leave")]
    LeaveEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
    },
    #[serde(rename = "memberJoined")]
    MemberJoinedEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken")]
        reply_token: String,
        #[serde(rename = "joined")]
        joined: Box<models::JoinedMembers>,
    },
    #[serde(rename = "memberLeft")]
    MemberLeftEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "left")]
        left: Box<models::LeftMembers>,
    },
    #[serde(rename = "postback")]
    PostbackEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken", skip_serializing_if = "Option::is_none")]
        reply_token: Option<String>,
        #[serde(rename = "postback")]
        postback: Box<models::PostbackContent>,
    },
    #[serde(rename = "videoPlayComplete")]
    VideoPlayCompleteEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken")]
        reply_token: String,
        #[serde(rename = "videoPlayComplete")]
        video_play_complete: Box<models::VideoPlayComplete>,
    },
    #[serde(rename = "beacon")]
    BeaconEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken")]
        reply_token: String,
        #[serde(rename = "beacon")]
        beacon: Box<models::BeaconContent>,
    },
    #[serde(rename = "accountLink")]
    AccountLinkEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken", skip_serializing_if = "Option::is_none")]
        reply_token: Option<String>,
        #[serde(rename = "link")]
        link: Box<models::LinkContent>,
    },
    #[serde(rename = "membership")]
    MembershipEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "replyToken")]
        reply_token: String,
        #[serde(rename = "membership")]
        membership: Box<models::MembershipContent>,
    },
    #[serde(rename = "module")]
    ModuleEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "module")]
        module: Box<models::ModuleContent>,
    },
    #[serde(rename = "activated")]
    ActivatedEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "chatControl")]
        chat_control: Box<models::ChatControl>,
    },
    #[serde(rename = "deactivated")]
    DeactivatedEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
    },
    #[serde(rename = "botSuspended")]
    BotSuspendedEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
    },
    #[serde(rename = "botResumed")]
    BotResumedEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
    },
    #[serde(rename = "delivery")]
    PnpDeliveryCompletionEvent {
        #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
        source: Option<Box<models::Source>>,
        #[serde(rename = "timestamp")]
        timestamp: i64,
        #[serde(rename = "mode")]
        mode: models::EventMode,
        #[serde(rename = "webhookEventId")]
        webhook_event_id: String,
        #[serde(rename = "deliveryContext")]
        delivery_context: Box<models::DeliveryContext>,
        #[serde(rename = "delivery")]
        delivery: Box<models::PnpDelivery>,
    },
}

impl Default for Event {
    fn default() -> Self {
        // Using the first variant as default
        Self::MessageEvent {
            source: None,
            timestamp: Default::default(),
            mode: Default::default(),
            webhook_event_id: String::new(),
            delivery_context: Box::new(Default::default()),
            reply_token: None,
            message: Box::new(Default::default()),
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::MessageEvent> for Event {
    fn from(value: models::MessageEvent) -> Self {
        Event::MessageEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            message: value.message,
        }
    }
}

impl From<models::UnsendEvent> for Event {
    fn from(value: models::UnsendEvent) -> Self {
        Event::UnsendEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            unsend: value.unsend,
        }
    }
}

impl From<models::FollowEvent> for Event {
    fn from(value: models::FollowEvent) -> Self {
        Event::FollowEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            follow: value.follow,
        }
    }
}

impl From<models::UnfollowEvent> for Event {
    fn from(value: models::UnfollowEvent) -> Self {
        Event::UnfollowEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
        }
    }
}

impl From<models::JoinEvent> for Event {
    fn from(value: models::JoinEvent) -> Self {
        Event::JoinEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
        }
    }
}

impl From<models::LeaveEvent> for Event {
    fn from(value: models::LeaveEvent) -> Self {
        Event::LeaveEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
        }
    }
}

impl From<models::MemberJoinedEvent> for Event {
    fn from(value: models::MemberJoinedEvent) -> Self {
        Event::MemberJoinedEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            joined: value.joined,
        }
    }
}

impl From<models::MemberLeftEvent> for Event {
    fn from(value: models::MemberLeftEvent) -> Self {
        Event::MemberLeftEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            left: value.left,
        }
    }
}

impl From<models::PostbackEvent> for Event {
    fn from(value: models::PostbackEvent) -> Self {
        Event::PostbackEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            postback: value.postback,
        }
    }
}

impl From<models::VideoPlayCompleteEvent> for Event {
    fn from(value: models::VideoPlayCompleteEvent) -> Self {
        Event::VideoPlayCompleteEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            video_play_complete: value.video_play_complete,
        }
    }
}

impl From<models::BeaconEvent> for Event {
    fn from(value: models::BeaconEvent) -> Self {
        Event::BeaconEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            beacon: value.beacon,
        }
    }
}

impl From<models::AccountLinkEvent> for Event {
    fn from(value: models::AccountLinkEvent) -> Self {
        Event::AccountLinkEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            link: value.link,
        }
    }
}

impl From<models::MembershipEvent> for Event {
    fn from(value: models::MembershipEvent) -> Self {
        Event::MembershipEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            reply_token: value.reply_token,
            membership: value.membership,
        }
    }
}

impl From<models::ModuleEvent> for Event {
    fn from(value: models::ModuleEvent) -> Self {
        Event::ModuleEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            module: value.module,
        }
    }
}

impl From<models::ActivatedEvent> for Event {
    fn from(value: models::ActivatedEvent) -> Self {
        Event::ActivatedEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            chat_control: value.chat_control,
        }
    }
}

impl From<models::DeactivatedEvent> for Event {
    fn from(value: models::DeactivatedEvent) -> Self {
        Event::DeactivatedEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
        }
    }
}

impl From<models::BotSuspendedEvent> for Event {
    fn from(value: models::BotSuspendedEvent) -> Self {
        Event::BotSuspendedEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
        }
    }
}

impl From<models::BotResumedEvent> for Event {
    fn from(value: models::BotResumedEvent) -> Self {
        Event::BotResumedEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
        }
    }
}

impl From<models::PnpDeliveryCompletionEvent> for Event {
    fn from(value: models::PnpDeliveryCompletionEvent) -> Self {
        Event::PnpDeliveryCompletionEvent {
            source: value.source,
            timestamp: value.timestamp,
            mode: value.mode,
            webhook_event_id: value.webhook_event_id,
            delivery_context: value.delivery_context,
            delivery: value.delivery,
        }
    }
}
