/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileMessageContent {
    /// Type
    #[serde(rename = "type")]
    pub r#type: String,
    /// Message ID
    #[serde(rename = "id")]
    pub id: String,
    /// File name
    #[serde(rename = "fileName")]
    pub file_name: String,
    /// File size in bytes
    #[serde(rename = "fileSize")]
    pub file_size: i32,
    /// Token used to mark the message as read.
    #[serde(rename = "markAsReadToken", skip_serializing_if = "Option::is_none")]
    pub mark_as_read_token: Option<String>,
}

impl FileMessageContent {
    pub fn new(
        r#type: String,
        id: String,
        file_name: String,
        file_size: i32,
    ) -> FileMessageContent {
        FileMessageContent {
            r#type,
            id,
            file_name,
            file_size,
            mark_as_read_token: None,
        }
    }
}
