/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MembershipContent enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MembershipContent {
    JoinedMembershipContent(Box<models::JoinedMembershipContent>),
    LeftMembershipContent(Box<models::LeftMembershipContent>),
    RenewedMembershipContent(Box<models::RenewedMembershipContent>),
}

impl Default for MembershipContent {
    fn default() -> Self {
        Self::JoinedMembershipContent(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::JoinedMembershipContent> for MembershipContent {
    fn from(value: models::JoinedMembershipContent) -> Self {
        MembershipContent::JoinedMembershipContent(Box::new(value))
    }
}

impl From<models::LeftMembershipContent> for MembershipContent {
    fn from(value: models::LeftMembershipContent) -> Self {
        MembershipContent::LeftMembershipContent(Box::new(value))
    }
}

impl From<models::RenewedMembershipContent> for MembershipContent {
    fn from(value: models::RenewedMembershipContent) -> Self {
        MembershipContent::RenewedMembershipContent(Box::new(value))
    }
}
