/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MembershipContent enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MembershipContent {
    #[serde(rename = "joined")]
    JoinedMembershipContent {
        #[serde(rename = "membershipId")]
        membership_id: i32,
    },
    #[serde(rename = "left")]
    LeftMembershipContent {
        #[serde(rename = "membershipId")]
        membership_id: i32,
    },
    #[serde(rename = "renewed")]
    RenewedMembershipContent {
        #[serde(rename = "membershipId")]
        membership_id: i32,
    },
}

impl Default for MembershipContent {
    fn default() -> Self {
        // Using the first variant as default
        Self::JoinedMembershipContent {
            membership_id: Default::default(),
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::JoinedMembershipContent> for MembershipContent {
    fn from(value: models::JoinedMembershipContent) -> Self {
        MembershipContent::JoinedMembershipContent {
            membership_id: value.membership_id,
        }
    }
}

impl From<models::LeftMembershipContent> for MembershipContent {
    fn from(value: models::LeftMembershipContent) -> Self {
        MembershipContent::LeftMembershipContent {
            membership_id: value.membership_id,
        }
    }
}

impl From<models::RenewedMembershipContent> for MembershipContent {
    fn from(value: models::RenewedMembershipContent) -> Self {
        MembershipContent::RenewedMembershipContent {
            membership_id: value.membership_id,
        }
    }
}
