/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Mentionee enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Mentionee {
    #[serde(rename = "user")]
    UserMentionee {
        #[serde(rename = "index")]
        index: i32,
        #[serde(rename = "length")]
        length: i32,
        #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
        user_id: Option<String>,
        #[serde(rename = "isSelf", skip_serializing_if = "Option::is_none")]
        is_self: Option<bool>,
    },
    #[serde(rename = "all")]
    AllMentionee {
        #[serde(rename = "index")]
        index: i32,
        #[serde(rename = "length")]
        length: i32,
    },
}

impl Default for Mentionee {
    fn default() -> Self {
        // Using the first variant as default
        Self::UserMentionee {
            index: Default::default(),
            length: Default::default(),
            user_id: None,
            is_self: None,
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::UserMentionee> for Mentionee {
    fn from(value: models::UserMentionee) -> Self {
        Mentionee::UserMentionee {
            index: value.index,
            length: value.length,
            user_id: value.user_id,
            is_self: value.is_self,
        }
    }
}

impl From<models::AllMentionee> for Mentionee {
    fn from(value: models::AllMentionee) -> Self {
        Mentionee::AllMentionee {
            index: value.index,
            length: value.length,
        }
    }
}
