/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessageContent enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    TextMessageContent(Box<models::TextMessageContent>),
    ImageMessageContent(Box<models::ImageMessageContent>),
    VideoMessageContent(Box<models::VideoMessageContent>),
    AudioMessageContent(Box<models::AudioMessageContent>),
    FileMessageContent(Box<models::FileMessageContent>),
    LocationMessageContent(Box<models::LocationMessageContent>),
    StickerMessageContent(Box<models::StickerMessageContent>),
}

impl Default for MessageContent {
    fn default() -> Self {
        Self::TextMessageContent(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::TextMessageContent> for MessageContent {
    fn from(value: models::TextMessageContent) -> Self {
        MessageContent::TextMessageContent(Box::new(value))
    }
}

impl From<models::ImageMessageContent> for MessageContent {
    fn from(value: models::ImageMessageContent) -> Self {
        MessageContent::ImageMessageContent(Box::new(value))
    }
}

impl From<models::VideoMessageContent> for MessageContent {
    fn from(value: models::VideoMessageContent) -> Self {
        MessageContent::VideoMessageContent(Box::new(value))
    }
}

impl From<models::AudioMessageContent> for MessageContent {
    fn from(value: models::AudioMessageContent) -> Self {
        MessageContent::AudioMessageContent(Box::new(value))
    }
}

impl From<models::FileMessageContent> for MessageContent {
    fn from(value: models::FileMessageContent) -> Self {
        MessageContent::FileMessageContent(Box::new(value))
    }
}

impl From<models::LocationMessageContent> for MessageContent {
    fn from(value: models::LocationMessageContent) -> Self {
        MessageContent::LocationMessageContent(Box::new(value))
    }
}

impl From<models::StickerMessageContent> for MessageContent {
    fn from(value: models::StickerMessageContent) -> Self {
        MessageContent::StickerMessageContent(Box::new(value))
    }
}
