/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModuleContent enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModuleContent {
    AttachedModuleContent(Box<models::AttachedModuleContent>),
    DetachedModuleContent(Box<models::DetachedModuleContent>),
}

impl Default for ModuleContent {
    fn default() -> Self {
        Self::AttachedModuleContent(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::AttachedModuleContent> for ModuleContent {
    fn from(value: models::AttachedModuleContent) -> Self {
        ModuleContent::AttachedModuleContent(Box::new(value))
    }
}

impl From<models::DetachedModuleContent> for ModuleContent {
    fn from(value: models::DetachedModuleContent) -> Self {
        ModuleContent::DetachedModuleContent(Box::new(value))
    }
}
