/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Source enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Source {
    UserSource(Box<models::UserSource>),
    GroupSource(Box<models::GroupSource>),
    RoomSource(Box<models::RoomSource>),
}

impl Default for Source {
    fn default() -> Self {
        Self::UserSource(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::UserSource> for Source {
    fn from(value: models::UserSource) -> Self {
        Source::UserSource(Box::new(value))
    }
}

impl From<models::GroupSource> for Source {
    fn from(value: models::GroupSource) -> Self {
        Source::GroupSource(Box::new(value))
    }
}

impl From<models::RoomSource> for Source {
    fn from(value: models::RoomSource) -> Self {
        Source::RoomSource(Box::new(value))
    }
}
