/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Source enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Source {
    #[serde(rename = "user")]
    UserSource {
        #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
        user_id: Option<String>,
    },
    #[serde(rename = "group")]
    GroupSource {
        #[serde(rename = "groupId")]
        group_id: String,
        #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
        user_id: Option<String>,
    },
    #[serde(rename = "room")]
    RoomSource {
        #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
        user_id: Option<String>,
        #[serde(rename = "roomId")]
        room_id: String,
    },
}

impl Default for Source {
    fn default() -> Self {
        // Using the first variant as default
        Self::UserSource { user_id: None }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::UserSource> for Source {
    fn from(value: models::UserSource) -> Self {
        Source::UserSource {
            user_id: value.user_id,
        }
    }
}

impl From<models::GroupSource> for Source {
    fn from(value: models::GroupSource) -> Self {
        Source::GroupSource {
            group_id: value.group_id,
            user_id: value.user_id,
        }
    }
}

impl From<models::RoomSource> for Source {
    fn from(value: models::RoomSource) -> Self {
        Source::RoomSource {
            user_id: value.user_id,
            room_id: value.room_id,
        }
    }
}
