/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`add_user_ids_to_audience`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddUserIdsToAudienceError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_audience_for_uploading_user_ids`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAudienceForUploadingUserIdsError {
    UnknownValue(serde_json::Value),
}

/// Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by file).
pub async fn add_user_ids_to_audience(
    configuration: &configuration::Configuration,
    file: std::path::PathBuf,
    audience_group_id: Option<i64>,
    upload_description: Option<&str>,
) -> Result<(), Error<AddUserIdsToAudienceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_file = file;
    let p_form_audience_group_id = audience_group_id;
    let p_form_upload_description = upload_description;

    let uri_str = format!(
        "{}/v2/bot/audienceGroup/upload/byFile",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    if let Some(param_value) = p_form_audience_group_id {
        multipart_form = multipart_form.text("audienceGroupId", param_value.to_string());
    }
    if let Some(param_value) = p_form_upload_description {
        multipart_form = multipart_form.text("uploadDescription", param_value.to_string());
    }
    // TODO: support file upload for 'file' parameter
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AddUserIdsToAudienceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Create audience for uploading user IDs (by file).
pub async fn create_audience_for_uploading_user_ids(
    configuration: &configuration::Configuration,
    file: std::path::PathBuf,
    description: Option<&str>,
    is_ifa_audience: Option<bool>,
    upload_description: Option<&str>,
) -> Result<models::CreateAudienceGroupResponse, Error<CreateAudienceForUploadingUserIdsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_file = file;
    let p_form_description = description;
    let p_form_is_ifa_audience = is_ifa_audience;
    let p_form_upload_description = upload_description;

    let uri_str = format!(
        "{}/v2/bot/audienceGroup/upload/byFile",
        configuration.base_path
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    if let Some(param_value) = p_form_description {
        multipart_form = multipart_form.text("description", param_value.to_string());
    }
    if let Some(param_value) = p_form_is_ifa_audience {
        multipart_form = multipart_form.text("isIfaAudience", param_value.to_string());
    }
    if let Some(param_value) = p_form_upload_description {
        multipart_form = multipart_form.text("uploadDescription", param_value.to_string());
    }
    // TODO: support file upload for 'file' parameter
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateAudienceGroupResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateAudienceGroupResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateAudienceForUploadingUserIdsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
