/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`add_audience_to_audience_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddAudienceToAudienceGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_audience_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAudienceGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_click_based_audience_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateClickBasedAudienceGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_imp_based_audience_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateImpBasedAudienceGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_audience_group`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAudienceGroupError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_audience_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAudienceDataError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_audience_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAudienceGroupsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_shared_audience_data`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSharedAudienceDataError {
    Status400(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_shared_audience_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSharedAudienceGroupsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_audience_group_description`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateAudienceGroupDescriptionError {
    UnknownValue(serde_json::Value),
}


/// Add user IDs or Identifiers for Advertisers (IFAs) to an audience for uploading user IDs (by JSON)
pub async fn add_audience_to_audience_group(configuration: &configuration::Configuration, add_audience_to_audience_group_request: models::AddAudienceToAudienceGroupRequest) -> Result<(), Error<AddAudienceToAudienceGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_add_audience_to_audience_group_request = add_audience_to_audience_group_request;

    let uri_str = format!("{}/v2/bot/audienceGroup/upload", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_add_audience_to_audience_group_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AddAudienceToAudienceGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create audience for uploading user IDs (by JSON)
pub async fn create_audience_group(configuration: &configuration::Configuration, create_audience_group_request: models::CreateAudienceGroupRequest) -> Result<models::CreateAudienceGroupResponse, Error<CreateAudienceGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_audience_group_request = create_audience_group_request;

    let uri_str = format!("{}/v2/bot/audienceGroup/upload", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_audience_group_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateAudienceGroupResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateAudienceGroupResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateAudienceGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create audience for click-based retargeting
pub async fn create_click_based_audience_group(configuration: &configuration::Configuration, create_click_based_audience_group_request: models::CreateClickBasedAudienceGroupRequest) -> Result<models::CreateClickBasedAudienceGroupResponse, Error<CreateClickBasedAudienceGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_click_based_audience_group_request = create_click_based_audience_group_request;

    let uri_str = format!("{}/v2/bot/audienceGroup/click", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_click_based_audience_group_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateClickBasedAudienceGroupResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateClickBasedAudienceGroupResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateClickBasedAudienceGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create audience for impression-based retargeting
pub async fn create_imp_based_audience_group(configuration: &configuration::Configuration, create_imp_based_audience_group_request: models::CreateImpBasedAudienceGroupRequest) -> Result<models::CreateImpBasedAudienceGroupResponse, Error<CreateImpBasedAudienceGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_imp_based_audience_group_request = create_imp_based_audience_group_request;

    let uri_str = format!("{}/v2/bot/audienceGroup/imp", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_imp_based_audience_group_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateImpBasedAudienceGroupResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateImpBasedAudienceGroupResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateImpBasedAudienceGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete audience
pub async fn delete_audience_group(configuration: &configuration::Configuration, audience_group_id: i64) -> Result<(), Error<DeleteAudienceGroupError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_audience_group_id = audience_group_id;

    let uri_str = format!("{}/v2/bot/audienceGroup/{audienceGroupId}", configuration.base_path, audienceGroupId=p_path_audience_group_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteAudienceGroupError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets audience data.
pub async fn get_audience_data(configuration: &configuration::Configuration, audience_group_id: i64) -> Result<models::GetAudienceDataResponse, Error<GetAudienceDataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_audience_group_id = audience_group_id;

    let uri_str = format!("{}/v2/bot/audienceGroup/{audienceGroupId}", configuration.base_path, audienceGroupId=p_path_audience_group_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetAudienceDataResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetAudienceDataResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAudienceDataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets data for more than one audience.
pub async fn get_audience_groups(configuration: &configuration::Configuration, page: i64, description: Option<&str>, status: Option<models::AudienceGroupStatus>, size: Option<i64>, includes_external_public_groups: Option<bool>, create_route: Option<models::AudienceGroupCreateRoute>) -> Result<models::GetAudienceGroupsResponse, Error<GetAudienceGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_description = description;
    let p_query_status = status;
    let p_query_size = size;
    let p_query_includes_external_public_groups = includes_external_public_groups;
    let p_query_create_route = create_route;

    let uri_str = format!("{}/v2/bot/audienceGroup/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("page", &p_query_page.to_string())]);
    if let Some(ref param_value) = p_query_description {
        req_builder = req_builder.query(&[("description", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_includes_external_public_groups {
        req_builder = req_builder.query(&[("includesExternalPublicGroups", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_create_route {
        req_builder = req_builder.query(&[("createRoute", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetAudienceGroupsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetAudienceGroupsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAudienceGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets audience data.
pub async fn get_shared_audience_data(configuration: &configuration::Configuration, audience_group_id: i64) -> Result<models::GetSharedAudienceDataResponse, Error<GetSharedAudienceDataError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_audience_group_id = audience_group_id;

    let uri_str = format!("{}/v2/bot/audienceGroup/shared/{audienceGroupId}", configuration.base_path, audienceGroupId=p_path_audience_group_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetSharedAudienceDataResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetSharedAudienceDataResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSharedAudienceDataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets data for more than one audience, including those shared by the Business Manager.
pub async fn get_shared_audience_groups(configuration: &configuration::Configuration, page: i64, description: Option<&str>, status: Option<models::AudienceGroupStatus>, size: Option<i64>, create_route: Option<models::AudienceGroupCreateRoute>, includes_owned_audience_groups: Option<bool>) -> Result<models::GetSharedAudienceGroupsResponse, Error<GetSharedAudienceGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_description = description;
    let p_query_status = status;
    let p_query_size = size;
    let p_query_create_route = create_route;
    let p_query_includes_owned_audience_groups = includes_owned_audience_groups;

    let uri_str = format!("{}/v2/bot/audienceGroup/shared/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("page", &p_query_page.to_string())]);
    if let Some(ref param_value) = p_query_description {
        req_builder = req_builder.query(&[("description", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_create_route {
        req_builder = req_builder.query(&[("createRoute", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_includes_owned_audience_groups {
        req_builder = req_builder.query(&[("includesOwnedAudienceGroups", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetSharedAudienceGroupsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetSharedAudienceGroupsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSharedAudienceGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Renames an existing audience.
pub async fn update_audience_group_description(configuration: &configuration::Configuration, audience_group_id: i64, update_audience_group_description_request: models::UpdateAudienceGroupDescriptionRequest) -> Result<(), Error<UpdateAudienceGroupDescriptionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_audience_group_id = audience_group_id;
    let p_body_update_audience_group_description_request = update_audience_group_description_request;

    let uri_str = format!("{}/v2/bot/audienceGroup/{audienceGroupId}/updateDescription", configuration.base_path, audienceGroupId=p_path_audience_group_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_audience_group_description_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateAudienceGroupDescriptionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

