/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`attach_module`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttachModuleError {
    UnknownValue(serde_json::Value),
}

/// Attach by operation of the module channel provider
pub async fn attach_module(
    configuration: &configuration::Configuration,
    grant_type: &str,
    code: &str,
    redirect_uri: &str,
    code_verifier: Option<&str>,
    client_id: Option<&str>,
    client_secret: Option<&str>,
    region: Option<&str>,
    basic_search_id: Option<&str>,
    scope: Option<&str>,
    brand_type: Option<&str>,
) -> Result<models::AttachModuleResponse, Error<AttachModuleError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_grant_type = grant_type;
    let p_form_code = code;
    let p_form_redirect_uri = redirect_uri;
    let p_form_code_verifier = code_verifier;
    let p_form_client_id = client_id;
    let p_form_client_secret = client_secret;
    let p_form_region = region;
    let p_form_basic_search_id = basic_search_id;
    let p_form_scope = scope;
    let p_form_brand_type = brand_type;

    let uri_str = format!("{}/module/auth/v1/token", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("grant_type", p_form_grant_type.to_string());
    multipart_form_params.insert("code", p_form_code.to_string());
    multipart_form_params.insert("redirect_uri", p_form_redirect_uri.to_string());
    if let Some(param_value) = p_form_code_verifier {
        multipart_form_params.insert("code_verifier", param_value.to_string());
    }
    if let Some(param_value) = p_form_client_id {
        multipart_form_params.insert("client_id", param_value.to_string());
    }
    if let Some(param_value) = p_form_client_secret {
        multipart_form_params.insert("client_secret", param_value.to_string());
    }
    if let Some(param_value) = p_form_region {
        multipart_form_params.insert("region", param_value.to_string());
    }
    if let Some(param_value) = p_form_basic_search_id {
        multipart_form_params.insert("basic_search_id", param_value.to_string());
    }
    if let Some(param_value) = p_form_scope {
        multipart_form_params.insert("scope", param_value.to_string());
    }
    if let Some(param_value) = p_form_brand_type {
        multipart_form_params.insert("brand_type", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AttachModuleResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AttachModuleResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AttachModuleError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
