/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AcquisitionConditionRequest enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AcquisitionConditionRequest {
    NormalAcquisitionConditionRequest(Box<models::NormalAcquisitionConditionRequest>),
    LotteryAcquisitionConditionRequest(Box<models::LotteryAcquisitionConditionRequest>),
}

impl Default for AcquisitionConditionRequest {
    fn default() -> Self {
        Self::NormalAcquisitionConditionRequest(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::NormalAcquisitionConditionRequest> for AcquisitionConditionRequest {
    fn from(value: models::NormalAcquisitionConditionRequest) -> Self {
        AcquisitionConditionRequest::NormalAcquisitionConditionRequest(Box::new(value))
    }
}

impl From<models::LotteryAcquisitionConditionRequest> for AcquisitionConditionRequest {
    fn from(value: models::LotteryAcquisitionConditionRequest) -> Self {
        AcquisitionConditionRequest::LotteryAcquisitionConditionRequest(Box::new(value))
    }
}
