/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AcquisitionConditionRequest {
    #[serde(rename="lottery")]
    LotteryAcquisitionConditionRequest {
    },
    #[serde(rename="normal")]
    NormalAcquisitionConditionRequest {
    },
}

impl Default for AcquisitionConditionRequest {
    fn default() -> Self {
        Self::LotteryAcquisitionConditionRequest {
        }
        
    }
}


