/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AcquisitionConditionResponse {
    #[serde(rename="lottery")]
    LotteryAcquisitionConditionResponse {
    },
    #[serde(rename="normal")]
    NormalAcquisitionConditionResponse {
    },
    #[serde(rename="referral")]
    ReferralAcquisitionConditionResponse {
    },
}

impl Default for AcquisitionConditionResponse {
    fn default() -> Self {
        Self::LotteryAcquisitionConditionResponse {
        }
        
    }
}


