/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AcquisitionConditionRequest enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AcquisitionConditionRequest {
    #[serde(rename = "normal")]
    NormalAcquisitionConditionRequest,
    #[serde(rename = "lottery")]
    LotteryAcquisitionConditionRequest {
        #[serde(rename = "lotteryProbability")]
        lottery_probability: i32,
        #[serde(rename = "maxAcquireCount")]
        max_acquire_count: i32,
    },
}

impl Default for AcquisitionConditionRequest {
    fn default() -> Self {
        // Using the first variant as default
        Self::NormalAcquisitionConditionRequest
    }
}

// Conversion methods from struct types to enum variants
impl From<models::NormalAcquisitionConditionRequest> for AcquisitionConditionRequest {
    fn from(value: models::NormalAcquisitionConditionRequest) -> Self {
        AcquisitionConditionRequest::NormalAcquisitionConditionRequest {}
    }
}

impl From<models::LotteryAcquisitionConditionRequest> for AcquisitionConditionRequest {
    fn from(value: models::LotteryAcquisitionConditionRequest) -> Self {
        AcquisitionConditionRequest::LotteryAcquisitionConditionRequest {
            lottery_probability: value.lottery_probability,
            max_acquire_count: value.max_acquire_count,
        }
    }
}
