/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AcquisitionConditionResponse enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AcquisitionConditionResponse {
    #[serde(rename = "normal")]
    NormalAcquisitionConditionResponse,
    #[serde(rename = "lottery")]
    LotteryAcquisitionConditionResponse {
        #[serde(rename = "lotteryProbability", skip_serializing_if = "Option::is_none")]
        lottery_probability: Option<i32>,
        #[serde(rename = "maxAcquireCount", skip_serializing_if = "Option::is_none")]
        max_acquire_count: Option<i32>,
    },
    #[serde(rename = "referral")]
    ReferralAcquisitionConditionResponse,
}

impl Default for AcquisitionConditionResponse {
    fn default() -> Self {
        // Using the first variant as default
        Self::NormalAcquisitionConditionResponse
    }
}

// Conversion methods from struct types to enum variants
impl From<models::NormalAcquisitionConditionResponse> for AcquisitionConditionResponse {
    fn from(value: models::NormalAcquisitionConditionResponse) -> Self {
        AcquisitionConditionResponse::NormalAcquisitionConditionResponse {}
    }
}

impl From<models::LotteryAcquisitionConditionResponse> for AcquisitionConditionResponse {
    fn from(value: models::LotteryAcquisitionConditionResponse) -> Self {
        AcquisitionConditionResponse::LotteryAcquisitionConditionResponse {
            lottery_probability: value.lottery_probability,
            max_acquire_count: value.max_acquire_count,
        }
    }
}

impl From<models::ReferralAcquisitionConditionResponse> for AcquisitionConditionResponse {
    fn from(value: models::ReferralAcquisitionConditionResponse) -> Self {
        AcquisitionConditionResponse::ReferralAcquisitionConditionResponse {}
    }
}
