/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AcquisitionConditionResponse enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AcquisitionConditionResponse {
    NormalAcquisitionConditionResponse(Box<models::NormalAcquisitionConditionResponse>),
    LotteryAcquisitionConditionResponse(Box<models::LotteryAcquisitionConditionResponse>),
    ReferralAcquisitionConditionResponse(Box<models::ReferralAcquisitionConditionResponse>),
}

impl Default for AcquisitionConditionResponse {
    fn default() -> Self {
        Self::NormalAcquisitionConditionResponse(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::NormalAcquisitionConditionResponse> for AcquisitionConditionResponse {
    fn from(value: models::NormalAcquisitionConditionResponse) -> Self {
        AcquisitionConditionResponse::NormalAcquisitionConditionResponse(Box::new(value))
    }
}

impl From<models::LotteryAcquisitionConditionResponse> for AcquisitionConditionResponse {
    fn from(value: models::LotteryAcquisitionConditionResponse) -> Self {
        AcquisitionConditionResponse::LotteryAcquisitionConditionResponse(Box::new(value))
    }
}

impl From<models::ReferralAcquisitionConditionResponse> for AcquisitionConditionResponse {
    fn from(value: models::ReferralAcquisitionConditionResponse) -> Self {
        AcquisitionConditionResponse::ReferralAcquisitionConditionResponse(Box::new(value))
    }
}
