/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Action : Action
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Action {
    #[serde(rename="camera")]
    CameraAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="cameraRoll")]
    CameraRollAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="clipboard")]
    ClipboardAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="datetimepicker")]
    DatetimePickerAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="location")]
    LocationAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="message")]
    MessageAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="postback")]
    PostbackAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="richmenuswitch")]
    RichMenuSwitchAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename="uri")]
    UriAction {
        /// Label for the action.
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
}

impl Default for Action {
    fn default() -> Self {
        Self::CameraAction {
            label: Default::default(),
        }
        
    }
}


