/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Action : Action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Action {
    /// Type of action
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Label for the action.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl Action {
    /// Action
    pub fn new() -> Action {
        Action {
            r#type: None,
            label: None,
        }
    }
}
