/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllMentionTarget {
    /// Target to be mentioned
    #[serde(rename = "type")]
    pub r#type: String,
}

impl AllMentionTarget {
    pub fn new(r#type: String) -> AllMentionTarget {
        AllMentionTarget { r#type }
    }
}
