/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashBackPriceInfoRequest enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CashBackPriceInfoRequest {
    #[serde(rename = "fixed")]
    CashBackFixedPriceInfoRequest {
        #[serde(rename = "fixedAmount", skip_serializing_if = "Option::is_none")]
        fixed_amount: Option<i64>,
    },
    #[serde(rename = "percentage")]
    CashBackPercentagePriceInfoRequest {
        #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
        percentage: Option<i32>,
    },
}

impl Default for CashBackPriceInfoRequest {
    fn default() -> Self {
        // Using the first variant as default
        Self::CashBackFixedPriceInfoRequest { fixed_amount: None }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::CashBackFixedPriceInfoRequest> for CashBackPriceInfoRequest {
    fn from(value: models::CashBackFixedPriceInfoRequest) -> Self {
        CashBackPriceInfoRequest::CashBackFixedPriceInfoRequest {
            fixed_amount: value.fixed_amount,
        }
    }
}

impl From<models::CashBackPercentagePriceInfoRequest> for CashBackPriceInfoRequest {
    fn from(value: models::CashBackPercentagePriceInfoRequest) -> Self {
        CashBackPriceInfoRequest::CashBackPercentagePriceInfoRequest {
            percentage: value.percentage,
        }
    }
}
