/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashBackFixedPriceInfoResponse {
    #[serde(rename = "type")]
    pub r#type: String,
    /// Currency code (e.g., JPY, THB, TWD).
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Currency>,
    #[serde(rename = "fixedAmount", skip_serializing_if = "Option::is_none")]
    pub fixed_amount: Option<i64>,
}

impl CashBackFixedPriceInfoResponse {
    pub fn new(r#type: String) -> CashBackFixedPriceInfoResponse {
        CashBackFixedPriceInfoResponse {
            r#type,
            currency: None,
            fixed_amount: None,
        }
    }
}
/// Currency code (e.g., JPY, THB, TWD).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "JPY")]
    Jpy,
    #[serde(rename = "THB")]
    Thb,
    #[serde(rename = "TWD")]
    Twd,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Jpy
    }
}
