/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CashBackPriceInfoResponse {
    #[serde(rename="fixed")]
    CashBackFixedPriceInfoResponse {
    },
    #[serde(rename="percentage")]
    CashBackPercentagePriceInfoResponse {
    },
}

impl Default for CashBackPriceInfoResponse {
    fn default() -> Self {
        Self::CashBackFixedPriceInfoResponse {
        }
        
    }
}


