/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CashBackPriceInfoResponse {
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CashBackPriceInfoResponse {
    pub fn new(r#type: String) -> CashBackPriceInfoResponse {
        CashBackPriceInfoResponse { r#type }
    }
}
