/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CashBackPriceInfoRequest enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CashBackPriceInfoRequest {
    CashBackFixedPriceInfoRequest(Box<models::CashBackFixedPriceInfoRequest>),
    CashBackPercentagePriceInfoRequest(Box<models::CashBackPercentagePriceInfoRequest>),
}

impl Default for CashBackPriceInfoRequest {
    fn default() -> Self {
        Self::CashBackFixedPriceInfoRequest(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::CashBackFixedPriceInfoRequest> for CashBackPriceInfoRequest {
    fn from(value: models::CashBackFixedPriceInfoRequest) -> Self {
        CashBackPriceInfoRequest::CashBackFixedPriceInfoRequest(Box::new(value))
    }
}

impl From<models::CashBackPercentagePriceInfoRequest> for CashBackPriceInfoRequest {
    fn from(value: models::CashBackPercentagePriceInfoRequest) -> Self {
        CashBackPriceInfoRequest::CashBackPercentagePriceInfoRequest(Box::new(value))
    }
}
