/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponCashBackRewardResponse {
    /// Type of coupon. Determines the benefit provided.
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "priceInfo", skip_serializing_if = "Option::is_none")]
    pub price_info: Option<Box<models::CashBackPriceInfoResponse>>,
}

impl CouponCashBackRewardResponse {
    pub fn new(r#type: String) -> CouponCashBackRewardResponse {
        CouponCashBackRewardResponse {
            r#type,
            price_info: None,
        }
    }
}

