/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CouponRewardRequest enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CouponRewardRequest {
    #[serde(rename = "cashBack")]
    CouponCashBackRewardRequest {
        #[serde(rename = "priceInfo", skip_serializing_if = "Option::is_none")]
        price_info: Option<Box<models::CashBackPriceInfoRequest>>,
    },
    #[serde(rename = "discount")]
    CouponDiscountRewardRequest {
        #[serde(rename = "priceInfo", skip_serializing_if = "Option::is_none")]
        price_info: Option<Box<models::DiscountPriceInfoRequest>>,
    },
    #[serde(rename = "free")]
    CouponFreeRewardRequest,
    #[serde(rename = "gift")]
    CouponGiftRewardRequest,
    #[serde(rename = "others")]
    CouponOthersRewardRequest,
}

impl Default for CouponRewardRequest {
    fn default() -> Self {
        // Using the first variant as default
        Self::CouponCashBackRewardRequest { price_info: None }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::CouponCashBackRewardRequest> for CouponRewardRequest {
    fn from(value: models::CouponCashBackRewardRequest) -> Self {
        CouponRewardRequest::CouponCashBackRewardRequest {
            price_info: value.price_info,
        }
    }
}

impl From<models::CouponDiscountRewardRequest> for CouponRewardRequest {
    fn from(value: models::CouponDiscountRewardRequest) -> Self {
        CouponRewardRequest::CouponDiscountRewardRequest {
            price_info: value.price_info,
        }
    }
}

impl From<models::CouponFreeRewardRequest> for CouponRewardRequest {
    fn from(value: models::CouponFreeRewardRequest) -> Self {
        CouponRewardRequest::CouponFreeRewardRequest {}
    }
}

impl From<models::CouponGiftRewardRequest> for CouponRewardRequest {
    fn from(value: models::CouponGiftRewardRequest) -> Self {
        CouponRewardRequest::CouponGiftRewardRequest {}
    }
}

impl From<models::CouponOthersRewardRequest> for CouponRewardRequest {
    fn from(value: models::CouponOthersRewardRequest) -> Self {
        CouponRewardRequest::CouponOthersRewardRequest {}
    }
}
