/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponMessage {
    /// Type of message
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
    pub quick_reply: Option<Box<models::QuickReply>>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<Box<models::Sender>>,
    /// Unique identifier of the coupon.
    #[serde(rename = "couponId")]
    pub coupon_id: String,
    /// Delivery route tag information. It can be used for analysis in LINE OA Manager.
    #[serde(rename = "deliveryTag", skip_serializing_if = "Option::is_none")]
    pub delivery_tag: Option<String>,
}

impl CouponMessage {
    pub fn new(coupon_id: String) -> CouponMessage {
        CouponMessage {
            r#type: None,
            quick_reply: None,
            sender: None,
            coupon_id,
            delivery_tag: None,
        }
    }
}

