/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponGiftRewardRequest {
    /// Type of coupon. Determines the benefit provided.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CouponGiftRewardRequest {
    pub fn new(r#type: String) -> CouponGiftRewardRequest {
        CouponGiftRewardRequest { r#type }
    }
}
