/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponOthersRewardRequest {
    /// Type of coupon. Determines the benefit provided.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CouponOthersRewardRequest {
    pub fn new(r#type: String) -> CouponOthersRewardRequest {
        CouponOthersRewardRequest {
            r#type,
        }
    }
}

