/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CouponRewardRequest {
    #[serde(rename="cashBack")]
    CouponCashBackRewardRequest {
    },
    #[serde(rename="discount")]
    CouponDiscountRewardRequest {
    },
    #[serde(rename="free")]
    CouponFreeRewardRequest {
    },
    #[serde(rename="gift")]
    CouponGiftRewardRequest {
    },
    #[serde(rename="others")]
    CouponOthersRewardRequest {
    },
}

impl Default for CouponRewardRequest {
    fn default() -> Self {
        Self::CouponCashBackRewardRequest {
        }
        
    }
}


