/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CouponCreateResponse : Response object returned after creating a coupon. Contains the coupon ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponCreateResponse {
    /// Unique identifier of the coupon.
    #[serde(rename = "couponId")]
    pub coupon_id: String,
}

impl CouponCreateResponse {
    /// Response object returned after creating a coupon. Contains the coupon ID.
    pub fn new(coupon_id: String) -> CouponCreateResponse {
        CouponCreateResponse { coupon_id }
    }
}
