/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CouponRewardResponse {
    #[serde(rename="cashBack")]
    CouponCashBackRewardResponse {
    },
    #[serde(rename="discount")]
    CouponDiscountRewardResponse {
    },
    #[serde(rename="free")]
    CouponFreeRewardResponse {
    },
    #[serde(rename="gift")]
    CouponGiftRewardResponse {
    },
    #[serde(rename="others")]
    CouponOthersRewardResponse {
    },
}

impl Default for CouponRewardResponse {
    fn default() -> Self {
        Self::CouponCashBackRewardResponse {
        }
        
    }
}


