/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DemographicFilter enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DemographicFilter {
    #[serde(rename = "age")]
    AgeDemographicFilter {
        #[serde(rename = "gte", skip_serializing_if = "Option::is_none")]
        gte: Option<models::AgeDemographic>,
        #[serde(rename = "lt", skip_serializing_if = "Option::is_none")]
        lt: Option<models::AgeDemographic>,
    },
    #[serde(rename = "appType")]
    AppTypeDemographicFilter {
        #[serde(rename = "oneOf", skip_serializing_if = "Option::is_none")]
        one_of: Option<Vec<models::AppTypeDemographic>>,
    },
    #[serde(rename = "area")]
    AreaDemographicFilter {
        #[serde(rename = "oneOf", skip_serializing_if = "Option::is_none")]
        one_of: Option<Vec<models::AreaDemographic>>,
    },
    #[serde(rename = "gender")]
    GenderDemographicFilter {
        #[serde(rename = "oneOf", skip_serializing_if = "Option::is_none")]
        one_of: Option<Vec<models::GenderDemographic>>,
    },
    #[serde(rename = "operator")]
    OperatorDemographicFilter {
        #[serde(rename = "and", skip_serializing_if = "Option::is_none")]
        and: Option<Vec<models::DemographicFilter>>,
        #[serde(rename = "or", skip_serializing_if = "Option::is_none")]
        or: Option<Vec<models::DemographicFilter>>,
        #[serde(rename = "not", skip_serializing_if = "Option::is_none")]
        not: Option<Box<models::DemographicFilter>>,
    },
    #[serde(rename = "subscriptionPeriod")]
    SubscriptionPeriodDemographicFilter {
        #[serde(rename = "gte", skip_serializing_if = "Option::is_none")]
        gte: Option<models::SubscriptionPeriodDemographic>,
        #[serde(rename = "lt", skip_serializing_if = "Option::is_none")]
        lt: Option<models::SubscriptionPeriodDemographic>,
    },
}

impl Default for DemographicFilter {
    fn default() -> Self {
        // Using the first variant as default
        Self::AgeDemographicFilter {
            gte: None,
            lt: None,
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::AgeDemographicFilter> for DemographicFilter {
    fn from(value: models::AgeDemographicFilter) -> Self {
        DemographicFilter::AgeDemographicFilter {
            gte: value.gte,
            lt: value.lt,
        }
    }
}

impl From<models::AppTypeDemographicFilter> for DemographicFilter {
    fn from(value: models::AppTypeDemographicFilter) -> Self {
        DemographicFilter::AppTypeDemographicFilter {
            one_of: value.one_of,
        }
    }
}

impl From<models::AreaDemographicFilter> for DemographicFilter {
    fn from(value: models::AreaDemographicFilter) -> Self {
        DemographicFilter::AreaDemographicFilter {
            one_of: value.one_of,
        }
    }
}

impl From<models::GenderDemographicFilter> for DemographicFilter {
    fn from(value: models::GenderDemographicFilter) -> Self {
        DemographicFilter::GenderDemographicFilter {
            one_of: value.one_of,
        }
    }
}

impl From<models::OperatorDemographicFilter> for DemographicFilter {
    fn from(value: models::OperatorDemographicFilter) -> Self {
        DemographicFilter::OperatorDemographicFilter {
            and: value.and,
            or: value.or,
            not: value.not,
        }
    }
}

impl From<models::SubscriptionPeriodDemographicFilter> for DemographicFilter {
    fn from(value: models::SubscriptionPeriodDemographicFilter) -> Self {
        DemographicFilter::SubscriptionPeriodDemographicFilter {
            gte: value.gte,
            lt: value.lt,
        }
    }
}
