/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DemographicFilter : Demographic filter
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DemographicFilter {
    #[serde(rename="age")]
    AgeDemographicFilter {
    },
    #[serde(rename="appType")]
    AppTypeDemographicFilter {
    },
    #[serde(rename="area")]
    AreaDemographicFilter {
    },
    #[serde(rename="gender")]
    GenderDemographicFilter {
    },
    #[serde(rename="operator")]
    OperatorDemographicFilter {
    },
    #[serde(rename="subscriptionPeriod")]
    SubscriptionPeriodDemographicFilter {
    },
}

impl Default for DemographicFilter {
    fn default() -> Self {
        Self::AgeDemographicFilter {
        }
        
    }
}


