/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DemographicFilter enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DemographicFilter {
    AgeDemographicFilter(Box<models::AgeDemographicFilter>),
    AppTypeDemographicFilter(Box<models::AppTypeDemographicFilter>),
    AreaDemographicFilter(Box<models::AreaDemographicFilter>),
    GenderDemographicFilter(Box<models::GenderDemographicFilter>),
    OperatorDemographicFilter(Box<models::OperatorDemographicFilter>),
    SubscriptionPeriodDemographicFilter(Box<models::SubscriptionPeriodDemographicFilter>),
}

impl Default for DemographicFilter {
    fn default() -> Self {
        Self::AgeDemographicFilter(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::AgeDemographicFilter> for DemographicFilter {
    fn from(value: models::AgeDemographicFilter) -> Self {
        DemographicFilter::AgeDemographicFilter(Box::new(value))
    }
}

impl From<models::AppTypeDemographicFilter> for DemographicFilter {
    fn from(value: models::AppTypeDemographicFilter) -> Self {
        DemographicFilter::AppTypeDemographicFilter(Box::new(value))
    }
}

impl From<models::AreaDemographicFilter> for DemographicFilter {
    fn from(value: models::AreaDemographicFilter) -> Self {
        DemographicFilter::AreaDemographicFilter(Box::new(value))
    }
}

impl From<models::GenderDemographicFilter> for DemographicFilter {
    fn from(value: models::GenderDemographicFilter) -> Self {
        DemographicFilter::GenderDemographicFilter(Box::new(value))
    }
}

impl From<models::OperatorDemographicFilter> for DemographicFilter {
    fn from(value: models::OperatorDemographicFilter) -> Self {
        DemographicFilter::OperatorDemographicFilter(Box::new(value))
    }
}

impl From<models::SubscriptionPeriodDemographicFilter> for DemographicFilter {
    fn from(value: models::SubscriptionPeriodDemographicFilter) -> Self {
        DemographicFilter::SubscriptionPeriodDemographicFilter(Box::new(value))
    }
}
