/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscountPriceInfoResponse enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DiscountPriceInfoResponse {
    DiscountFixedPriceInfoResponse(Box<models::DiscountFixedPriceInfoResponse>),
    DiscountPercentagePriceInfoResponse(Box<models::DiscountPercentagePriceInfoResponse>),
    DiscountExplicitPriceInfoResponse(Box<models::DiscountExplicitPriceInfoResponse>),
}

impl Default for DiscountPriceInfoResponse {
    fn default() -> Self {
        Self::DiscountFixedPriceInfoResponse(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::DiscountFixedPriceInfoResponse> for DiscountPriceInfoResponse {
    fn from(value: models::DiscountFixedPriceInfoResponse) -> Self {
        DiscountPriceInfoResponse::DiscountFixedPriceInfoResponse(Box::new(value))
    }
}

impl From<models::DiscountPercentagePriceInfoResponse> for DiscountPriceInfoResponse {
    fn from(value: models::DiscountPercentagePriceInfoResponse) -> Self {
        DiscountPriceInfoResponse::DiscountPercentagePriceInfoResponse(Box::new(value))
    }
}

impl From<models::DiscountExplicitPriceInfoResponse> for DiscountPriceInfoResponse {
    fn from(value: models::DiscountExplicitPriceInfoResponse) -> Self {
        DiscountPriceInfoResponse::DiscountExplicitPriceInfoResponse(Box::new(value))
    }
}
