/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DiscountPriceInfoResponse {
    #[serde(rename="explicit")]
    DiscountExplicitPriceInfoResponse {
    },
    #[serde(rename="fixed")]
    DiscountFixedPriceInfoResponse {
    },
    #[serde(rename="percentage")]
    DiscountPercentagePriceInfoResponse {
    },
}

impl Default for DiscountPriceInfoResponse {
    fn default() -> Self {
        Self::DiscountExplicitPriceInfoResponse {
        }
        
    }
}


