/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscountPriceInfoRequest enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DiscountPriceInfoRequest {
    #[serde(rename = "fixed")]
    DiscountFixedPriceInfoRequest {
        #[serde(rename = "fixedAmount", skip_serializing_if = "Option::is_none")]
        fixed_amount: Option<i64>,
    },
    #[serde(rename = "percentage")]
    DiscountPercentagePriceInfoRequest {
        #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
        percentage: Option<i32>,
    },
    #[serde(rename = "explicit")]
    DiscountExplicitPriceInfoRequest {
        #[serde(rename = "priceAfterDiscount", skip_serializing_if = "Option::is_none")]
        price_after_discount: Option<i64>,
        #[serde(rename = "originalPrice", skip_serializing_if = "Option::is_none")]
        original_price: Option<i64>,
    },
}

impl Default for DiscountPriceInfoRequest {
    fn default() -> Self {
        // Using the first variant as default
        Self::DiscountFixedPriceInfoRequest { fixed_amount: None }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::DiscountFixedPriceInfoRequest> for DiscountPriceInfoRequest {
    fn from(value: models::DiscountFixedPriceInfoRequest) -> Self {
        DiscountPriceInfoRequest::DiscountFixedPriceInfoRequest {
            fixed_amount: value.fixed_amount,
        }
    }
}

impl From<models::DiscountPercentagePriceInfoRequest> for DiscountPriceInfoRequest {
    fn from(value: models::DiscountPercentagePriceInfoRequest) -> Self {
        DiscountPriceInfoRequest::DiscountPercentagePriceInfoRequest {
            percentage: value.percentage,
        }
    }
}

impl From<models::DiscountExplicitPriceInfoRequest> for DiscountPriceInfoRequest {
    fn from(value: models::DiscountExplicitPriceInfoRequest) -> Self {
        DiscountPriceInfoRequest::DiscountExplicitPriceInfoRequest {
            price_after_discount: value.price_after_discount,
            original_price: value.original_price,
        }
    }
}
