/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DiscountPriceInfoRequest {
    #[serde(rename="explicit")]
    DiscountExplicitPriceInfoRequest {
    },
    #[serde(rename="fixed")]
    DiscountFixedPriceInfoRequest {
    },
    #[serde(rename="percentage")]
    DiscountPercentagePriceInfoRequest {
    },
}

impl Default for DiscountPriceInfoRequest {
    fn default() -> Self {
        Self::DiscountExplicitPriceInfoRequest {
        }
        
    }
}


