/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountExplicitPriceInfoRequest {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "priceAfterDiscount", skip_serializing_if = "Option::is_none")]
    pub price_after_discount: Option<i64>,
    #[serde(rename = "originalPrice", skip_serializing_if = "Option::is_none")]
    pub original_price: Option<i64>,
}

impl DiscountExplicitPriceInfoRequest {
    pub fn new(r#type: String) -> DiscountExplicitPriceInfoRequest {
        DiscountExplicitPriceInfoRequest {
            r#type,
            price_after_discount: None,
            original_price: None,
        }
    }
}

