/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountPercentagePriceInfoRequest {
    #[serde(rename = "type")]
    pub r#type: String,
    /// Specifies the discount rate as a percentage. Must be an integer between 1 and 99.
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<i32>,
}

impl DiscountPercentagePriceInfoRequest {
    pub fn new(r#type: String) -> DiscountPercentagePriceInfoRequest {
        DiscountPercentagePriceInfoRequest {
            r#type,
            percentage: None,
        }
    }
}

