/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountPercentagePriceInfoResponse {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<i32>,
}

impl DiscountPercentagePriceInfoResponse {
    pub fn new(r#type: String) -> DiscountPercentagePriceInfoResponse {
        DiscountPercentagePriceInfoResponse {
            r#type,
            percentage: None,
        }
    }
}

