/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DiscountPriceInfoRequest enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DiscountPriceInfoRequest {
    DiscountFixedPriceInfoRequest(Box<models::DiscountFixedPriceInfoRequest>),
    DiscountPercentagePriceInfoRequest(Box<models::DiscountPercentagePriceInfoRequest>),
    DiscountExplicitPriceInfoRequest(Box<models::DiscountExplicitPriceInfoRequest>),
}

impl Default for DiscountPriceInfoRequest {
    fn default() -> Self {
        Self::DiscountFixedPriceInfoRequest(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::DiscountFixedPriceInfoRequest> for DiscountPriceInfoRequest {
    fn from(value: models::DiscountFixedPriceInfoRequest) -> Self {
        DiscountPriceInfoRequest::DiscountFixedPriceInfoRequest(Box::new(value))
    }
}

impl From<models::DiscountPercentagePriceInfoRequest> for DiscountPriceInfoRequest {
    fn from(value: models::DiscountPercentagePriceInfoRequest) -> Self {
        DiscountPriceInfoRequest::DiscountPercentagePriceInfoRequest(Box::new(value))
    }
}

impl From<models::DiscountExplicitPriceInfoRequest> for DiscountPriceInfoRequest {
    fn from(value: models::DiscountExplicitPriceInfoRequest) -> Self {
        DiscountPriceInfoRequest::DiscountExplicitPriceInfoRequest(Box::new(value))
    }
}
