/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FlexCarousel {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "contents")]
    pub contents: Vec<models::FlexBubble>,
}

impl FlexCarousel {
    pub fn new(r#type: String, contents: Vec<models::FlexBubble>) -> FlexCarousel {
        FlexCarousel {
            r#type,
            contents,
        }
    }
}

