/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FlexComponent {
    #[serde(rename="box")]
    FlexBox {
    },
    #[serde(rename="button")]
    FlexButton {
    },
    #[serde(rename="filler")]
    FlexFiller {
    },
    #[serde(rename="icon")]
    FlexIcon {
    },
    #[serde(rename="image")]
    FlexImage {
    },
    #[serde(rename="separator")]
    FlexSeparator {
    },
    #[serde(rename="span")]
    FlexSpan {
    },
    #[serde(rename="text")]
    FlexText {
    },
    #[serde(rename="video")]
    FlexVideo {
    },
}

impl Default for FlexComponent {
    fn default() -> Self {
        Self::FlexBox {
        }
        
    }
}


