/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlexBoxBackground enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FlexBoxBackground {
    #[serde(rename = "linearGradient")]
    FlexBoxLinearGradient {
        #[serde(rename = "angle", skip_serializing_if = "Option::is_none")]
        angle: Option<String>,
        #[serde(rename = "startColor", skip_serializing_if = "Option::is_none")]
        start_color: Option<String>,
        #[serde(rename = "endColor", skip_serializing_if = "Option::is_none")]
        end_color: Option<String>,
        #[serde(rename = "centerColor", skip_serializing_if = "Option::is_none")]
        center_color: Option<String>,
        #[serde(rename = "centerPosition", skip_serializing_if = "Option::is_none")]
        center_position: Option<String>,
    },
}

impl Default for FlexBoxBackground {
    fn default() -> Self {
        // Using the first variant as default
        Self::FlexBoxLinearGradient {
            angle: None,
            start_color: None,
            end_color: None,
            center_color: None,
            center_position: None,
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::FlexBoxLinearGradient> for FlexBoxBackground {
    fn from(value: models::FlexBoxLinearGradient) -> Self {
        FlexBoxBackground::FlexBoxLinearGradient {
            angle: value.angle,
            start_color: value.start_color,
            end_color: value.end_color,
            center_color: value.center_color,
            center_position: value.center_position,
        }
    }
}
