/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum FlexBoxBackground {
    #[serde(rename="linearGradient")]
    FlexBoxLinearGradient {
    },
}

impl Default for FlexBoxBackground {
    fn default() -> Self {
        Self::FlexBoxLinearGradient {
        }
        
    }
}


