/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlexBoxBackground enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FlexBoxBackground {
    FlexBoxLinearGradient(Box<models::FlexBoxLinearGradient>),
}

impl Default for FlexBoxBackground {
    fn default() -> Self {
        Self::FlexBoxLinearGradient(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::FlexBoxLinearGradient> for FlexBoxBackground {
    fn from(value: models::FlexBoxLinearGradient) -> Self {
        FlexBoxBackground::FlexBoxLinearGradient(Box::new(value))
    }
}
