/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FlexContainer enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FlexContainer {
    FlexBubble(Box<models::FlexBubble>),
    FlexCarousel(Box<models::FlexCarousel>),
}

impl Default for FlexContainer {
    fn default() -> Self {
        Self::FlexBubble(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::FlexBubble> for FlexContainer {
    fn from(value: models::FlexBubble) -> Self {
        FlexContainer::FlexBubble(Box::new(value))
    }
}

impl From<models::FlexCarousel> for FlexContainer {
    fn from(value: models::FlexCarousel) -> Self {
        FlexContainer::FlexCarousel(Box::new(value))
    }
}
