/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ImagemapAction {
    #[serde(rename="clipboard")]
    ClipboardImagemapAction {
        #[serde(rename = "area")]
        area: Box<models::ImagemapArea>,
    },
    #[serde(rename="message")]
    MessageImagemapAction {
        #[serde(rename = "area")]
        area: Box<models::ImagemapArea>,
    },
    #[serde(rename="uri")]
    UriImagemapAction {
        #[serde(rename = "area")]
        area: Box<models::ImagemapArea>,
    },
}

impl Default for ImagemapAction {
    fn default() -> Self {
        Self::ClipboardImagemapAction {
            area: Default::default(),
        }
        
    }
}


