/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageCarouselTemplate {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "columns")]
    pub columns: Vec<models::ImageCarouselColumn>,
}

impl ImageCarouselTemplate {
    pub fn new(r#type: String, columns: Vec<models::ImageCarouselColumn>) -> ImageCarouselTemplate {
        ImageCarouselTemplate {
            r#type,
            columns,
        }
    }
}

