/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImagemapAction enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ImagemapAction {
    #[serde(rename = "message")]
    MessageImagemapAction {
        #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
        area: Option<Box<models::ImagemapArea>>,
        #[serde(rename = "text")]
        text: String,
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename = "uri")]
    UriImagemapAction {
        #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
        area: Option<Box<models::ImagemapArea>>,
        #[serde(rename = "linkUri")]
        link_uri: String,
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
    #[serde(rename = "clipboard")]
    ClipboardImagemapAction {
        #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
        area: Option<Box<models::ImagemapArea>>,
        #[serde(rename = "clipboardText")]
        clipboard_text: String,
        #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
        label: Option<String>,
    },
}

impl Default for ImagemapAction {
    fn default() -> Self {
        // Using the first variant as default
        Self::MessageImagemapAction {
            area: None,
            text: String::new(),
            label: None,
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::MessageImagemapAction> for ImagemapAction {
    fn from(value: models::MessageImagemapAction) -> Self {
        ImagemapAction::MessageImagemapAction {
            area: value.area,
            text: value.text,
            label: value.label,
        }
    }
}

impl From<models::UriImagemapAction> for ImagemapAction {
    fn from(value: models::UriImagemapAction) -> Self {
        ImagemapAction::UriImagemapAction {
            area: value.area,
            link_uri: value.link_uri,
            label: value.label,
        }
    }
}

impl From<models::ClipboardImagemapAction> for ImagemapAction {
    fn from(value: models::ClipboardImagemapAction) -> Self {
        ImagemapAction::ClipboardImagemapAction {
            area: value.area,
            clipboard_text: value.clipboard_text,
            label: value.label,
        }
    }
}
