/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LotteryAcquisitionConditionRequest {
    /// Determines how the coupon is distributed or used.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Probability (1-99) of winning the coupon in lottery-type campaigns.
    #[serde(rename = "lotteryProbability")]
    pub lottery_probability: i32,
    /// Maximum number of coupons that can be issued in total. Use -1 to indicate no limit
    #[serde(rename = "maxAcquireCount")]
    pub max_acquire_count: i32,
}

impl LotteryAcquisitionConditionRequest {
    pub fn new(
        r#type: String,
        lottery_probability: i32,
        max_acquire_count: i32,
    ) -> LotteryAcquisitionConditionRequest {
        LotteryAcquisitionConditionRequest {
            r#type,
            lottery_probability,
            max_acquire_count,
        }
    }
}
