/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarkMessagesAsReadByTokenRequest {
    /// Token used to mark messages as read.
    #[serde(rename = "markAsReadToken")]
    pub mark_as_read_token: String,
}

impl MarkMessagesAsReadByTokenRequest {
    pub fn new(mark_as_read_token: String) -> MarkMessagesAsReadByTokenRequest {
        MarkMessagesAsReadByTokenRequest { mark_as_read_token }
    }
}
