/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MentionTarget enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MentionTarget {
    #[serde(rename = "user")]
    UserMentionTarget {
        #[serde(rename = "userId")]
        user_id: String,
    },
    #[serde(rename = "all")]
    AllMentionTarget,
}

impl Default for MentionTarget {
    fn default() -> Self {
        // Using the first variant as default
        Self::UserMentionTarget {
            user_id: String::new(),
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::UserMentionTarget> for MentionTarget {
    fn from(value: models::UserMentionTarget) -> Self {
        MentionTarget::UserMentionTarget {
            user_id: value.user_id,
        }
    }
}

impl From<models::AllMentionTarget> for MentionTarget {
    fn from(value: models::AllMentionTarget) -> Self {
        MentionTarget::AllMentionTarget {}
    }
}
