/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MessagingApiPagerCouponListResponse : Paginated response object containing a list of coupons.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessagingApiPagerCouponListResponse {
    /// List of coupon summary objects.
    #[serde(rename = "items")]
    pub items: Vec<models::CouponListResponse>,
    /// Token for fetching the next page of results.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl MessagingApiPagerCouponListResponse {
    /// Paginated response object containing a list of coupons.
    pub fn new(items: Vec<models::CouponListResponse>) -> MessagingApiPagerCouponListResponse {
        MessagingApiPagerCouponListResponse { items, next: None }
    }
}
