/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageImagemapAction {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
    pub area: Option<Box<models::ImagemapArea>>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl MessageImagemapAction {
    pub fn new(text: String) -> MessageImagemapAction {
        MessageImagemapAction {
            r#type: None,
            area: None,
            text,
            label: None,
        }
    }
}

