/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Message enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Message {
    #[serde(rename = "text")]
    TextMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "text")]
        text: String,
        #[serde(rename = "emojis", skip_serializing_if = "Option::is_none")]
        emojis: Option<Vec<models::Emoji>>,
        #[serde(rename = "quoteToken", skip_serializing_if = "Option::is_none")]
        quote_token: Option<String>,
    },
    #[serde(rename = "textV2")]
    TextMessageV2 {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "text")]
        text: String,
        #[serde(rename = "substitution", skip_serializing_if = "Option::is_none")]
        substitution: Option<std::collections::HashMap<String, models::SubstitutionObject>>,
        #[serde(rename = "quoteToken", skip_serializing_if = "Option::is_none")]
        quote_token: Option<String>,
    },
    #[serde(rename = "sticker")]
    StickerMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "packageId")]
        package_id: String,
        #[serde(rename = "stickerId")]
        sticker_id: String,
        #[serde(rename = "quoteToken", skip_serializing_if = "Option::is_none")]
        quote_token: Option<String>,
    },
    #[serde(rename = "image")]
    ImageMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "originalContentUrl")]
        original_content_url: String,
        #[serde(rename = "previewImageUrl")]
        preview_image_url: String,
    },
    #[serde(rename = "video")]
    VideoMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "originalContentUrl")]
        original_content_url: String,
        #[serde(rename = "previewImageUrl")]
        preview_image_url: String,
        #[serde(rename = "trackingId", skip_serializing_if = "Option::is_none")]
        tracking_id: Option<String>,
    },
    #[serde(rename = "audio")]
    AudioMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "originalContentUrl")]
        original_content_url: String,
        #[serde(rename = "duration")]
        duration: i64,
    },
    #[serde(rename = "location")]
    LocationMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "title")]
        title: String,
        #[serde(rename = "address")]
        address: String,
        #[serde(rename = "latitude")]
        latitude: f64,
        #[serde(rename = "longitude")]
        longitude: f64,
    },
    #[serde(rename = "imagemap")]
    ImagemapMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "baseUrl")]
        base_url: String,
        #[serde(rename = "altText")]
        alt_text: String,
        #[serde(rename = "baseSize")]
        base_size: Box<models::ImagemapBaseSize>,
        #[serde(rename = "actions")]
        actions: Vec<models::ImagemapAction>,
        #[serde(rename = "video", skip_serializing_if = "Option::is_none")]
        video: Option<Box<models::ImagemapVideo>>,
    },
    #[serde(rename = "template")]
    TemplateMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "altText")]
        alt_text: String,
        #[serde(rename = "template")]
        template: Box<models::Template>,
    },
    #[serde(rename = "flex")]
    FlexMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "altText")]
        alt_text: String,
        #[serde(rename = "contents")]
        contents: Box<models::FlexContainer>,
    },
    #[serde(rename = "coupon")]
    CouponMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
        #[serde(rename = "couponId")]
        coupon_id: String,
        #[serde(rename = "deliveryTag", skip_serializing_if = "Option::is_none")]
        delivery_tag: Option<String>,
    },
}

impl Default for Message {
    fn default() -> Self {
        // Using the first variant as default
        Self::TextMessage {
            quick_reply: None,
            sender: None,
            text: String::new(),
            emojis: None,
            quote_token: None,
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::TextMessage> for Message {
    fn from(value: models::TextMessage) -> Self {
        Message::TextMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            text: value.text,
            emojis: value.emojis,
            quote_token: value.quote_token,
        }
    }
}

impl From<models::TextMessageV2> for Message {
    fn from(value: models::TextMessageV2) -> Self {
        Message::TextMessageV2 {
            quick_reply: value.quick_reply,
            sender: value.sender,
            text: value.text,
            substitution: value.substitution,
            quote_token: value.quote_token,
        }
    }
}

impl From<models::StickerMessage> for Message {
    fn from(value: models::StickerMessage) -> Self {
        Message::StickerMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            package_id: value.package_id,
            sticker_id: value.sticker_id,
            quote_token: value.quote_token,
        }
    }
}

impl From<models::ImageMessage> for Message {
    fn from(value: models::ImageMessage) -> Self {
        Message::ImageMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            original_content_url: value.original_content_url,
            preview_image_url: value.preview_image_url,
        }
    }
}

impl From<models::VideoMessage> for Message {
    fn from(value: models::VideoMessage) -> Self {
        Message::VideoMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            original_content_url: value.original_content_url,
            preview_image_url: value.preview_image_url,
            tracking_id: value.tracking_id,
        }
    }
}

impl From<models::AudioMessage> for Message {
    fn from(value: models::AudioMessage) -> Self {
        Message::AudioMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            original_content_url: value.original_content_url,
            duration: value.duration,
        }
    }
}

impl From<models::LocationMessage> for Message {
    fn from(value: models::LocationMessage) -> Self {
        Message::LocationMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            title: value.title,
            address: value.address,
            latitude: value.latitude,
            longitude: value.longitude,
        }
    }
}

impl From<models::ImagemapMessage> for Message {
    fn from(value: models::ImagemapMessage) -> Self {
        Message::ImagemapMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            base_url: value.base_url,
            alt_text: value.alt_text,
            base_size: value.base_size,
            actions: value.actions,
            video: value.video,
        }
    }
}

impl From<models::TemplateMessage> for Message {
    fn from(value: models::TemplateMessage) -> Self {
        Message::TemplateMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            alt_text: value.alt_text,
            template: value.template,
        }
    }
}

impl From<models::FlexMessage> for Message {
    fn from(value: models::FlexMessage) -> Self {
        Message::FlexMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            alt_text: value.alt_text,
            contents: value.contents,
        }
    }
}

impl From<models::CouponMessage> for Message {
    fn from(value: models::CouponMessage) -> Self {
        Message::CouponMessage {
            quick_reply: value.quick_reply,
            sender: value.sender,
            coupon_id: value.coupon_id,
            delivery_tag: value.delivery_tag,
        }
    }
}
