/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Message {
    #[serde(rename="audio")]
    AudioMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="coupon")]
    CouponMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="flex")]
    FlexMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="image")]
    ImageMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="imagemap")]
    ImagemapMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="location")]
    LocationMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="sticker")]
    StickerMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="template")]
    TemplateMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="text")]
    TextMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="textV2")]
    TextMessageV2 {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
    #[serde(rename="video")]
    VideoMessage {
        #[serde(rename = "quickReply", skip_serializing_if = "Option::is_none")]
        quick_reply: Option<Box<models::QuickReply>>,
        #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
        sender: Option<Box<models::Sender>>,
    },
}

impl Default for Message {
    fn default() -> Self {
        Self::AudioMessage {
            quick_reply: Default::default(),
            sender: Default::default(),
        }
        
    }
}


