/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NormalAcquisitionConditionResponse {
    /// Determines how the coupon is distributed or used.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl NormalAcquisitionConditionResponse {
    pub fn new(r#type: String) -> NormalAcquisitionConditionResponse {
        NormalAcquisitionConditionResponse {
            r#type,
        }
    }
}

