/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Recipient enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Recipient {
    #[serde(rename = "operator")]
    OperatorRecipient {
        #[serde(rename = "and", skip_serializing_if = "Option::is_none")]
        and: Option<Vec<models::Recipient>>,
        #[serde(rename = "or", skip_serializing_if = "Option::is_none")]
        or: Option<Vec<models::Recipient>>,
        #[serde(rename = "not", skip_serializing_if = "Option::is_none")]
        not: Option<Box<models::Recipient>>,
    },
    #[serde(rename = "audience")]
    AudienceRecipient {
        #[serde(rename = "audienceGroupId", skip_serializing_if = "Option::is_none")]
        audience_group_id: Option<i64>,
    },
    #[serde(rename = "redelivery")]
    RedeliveryRecipient {
        #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },
}

impl Default for Recipient {
    fn default() -> Self {
        // Using the first variant as default
        Self::OperatorRecipient {
            and: None,
            or: None,
            not: None,
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::OperatorRecipient> for Recipient {
    fn from(value: models::OperatorRecipient) -> Self {
        Recipient::OperatorRecipient {
            and: value.and,
            or: value.or,
            not: value.not,
        }
    }
}

impl From<models::AudienceRecipient> for Recipient {
    fn from(value: models::AudienceRecipient) -> Self {
        Recipient::AudienceRecipient {
            audience_group_id: value.audience_group_id,
        }
    }
}

impl From<models::RedeliveryRecipient> for Recipient {
    fn from(value: models::RedeliveryRecipient) -> Self {
        Recipient::RedeliveryRecipient {
            request_id: value.request_id,
        }
    }
}
