/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Recipient enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Recipient {
    OperatorRecipient(Box<models::OperatorRecipient>),
    AudienceRecipient(Box<models::AudienceRecipient>),
    RedeliveryRecipient(Box<models::RedeliveryRecipient>),
}

impl Default for Recipient {
    fn default() -> Self {
        Self::OperatorRecipient(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::OperatorRecipient> for Recipient {
    fn from(value: models::OperatorRecipient) -> Self {
        Recipient::OperatorRecipient(Box::new(value))
    }
}

impl From<models::AudienceRecipient> for Recipient {
    fn from(value: models::AudienceRecipient) -> Self {
        Recipient::AudienceRecipient(Box::new(value))
    }
}

impl From<models::RedeliveryRecipient> for Recipient {
    fn from(value: models::RedeliveryRecipient) -> Self {
        Recipient::RedeliveryRecipient(Box::new(value))
    }
}
