/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RichMenuBatchOperation : Rich menu operation object represents the batch operation to the rich menu linked to the user.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RichMenuBatchOperation {
    #[serde(rename="link")]
    RichMenuBatchLinkOperation {
    },
    #[serde(rename="unlink")]
    RichMenuBatchUnlinkOperation {
    },
    #[serde(rename="unlinkAll")]
    RichMenuBatchUnlinkAllOperation {
    },
}

impl Default for RichMenuBatchOperation {
    fn default() -> Self {
        Self::RichMenuBatchLinkOperation {
        }
        
    }
}


