/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RichMenuBatchOperation enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RichMenuBatchOperation {
    #[serde(rename = "link")]
    RichMenuBatchLinkOperation {
        #[serde(rename = "from")]
        from: String,
        #[serde(rename = "to")]
        to: String,
    },
    #[serde(rename = "unlink")]
    RichMenuBatchUnlinkOperation {
        #[serde(rename = "from")]
        from: String,
    },
    #[serde(rename = "unlinkAll")]
    RichMenuBatchUnlinkAllOperation,
}

impl Default for RichMenuBatchOperation {
    fn default() -> Self {
        // Using the first variant as default
        Self::RichMenuBatchLinkOperation {
            from: String::new(),
            to: String::new(),
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::RichMenuBatchLinkOperation> for RichMenuBatchOperation {
    fn from(value: models::RichMenuBatchLinkOperation) -> Self {
        RichMenuBatchOperation::RichMenuBatchLinkOperation {
            from: value.from,
            to: value.to,
        }
    }
}

impl From<models::RichMenuBatchUnlinkOperation> for RichMenuBatchOperation {
    fn from(value: models::RichMenuBatchUnlinkOperation) -> Self {
        RichMenuBatchOperation::RichMenuBatchUnlinkOperation { from: value.from }
    }
}

impl From<models::RichMenuBatchUnlinkAllOperation> for RichMenuBatchOperation {
    fn from(value: models::RichMenuBatchUnlinkAllOperation) -> Self {
        RichMenuBatchOperation::RichMenuBatchUnlinkAllOperation {}
    }
}
