/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RichMenuBatchLinkOperation : Replace the rich menu with the rich menu specified in the `to` property for all users linked to the rich menu specified in the `from` property.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RichMenuBatchLinkOperation {
    /// The type of operation to the rich menu linked to the user. One of link, unlink, or unlinkAll.
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "to")]
    pub to: String,
}

impl RichMenuBatchLinkOperation {
    /// Replace the rich menu with the rich menu specified in the `to` property for all users linked to the rich menu specified in the `from` property.
    pub fn new(r#type: String, from: String, to: String) -> RichMenuBatchLinkOperation {
        RichMenuBatchLinkOperation {
            r#type,
            from,
            to,
        }
    }
}

