/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RichMenuBatchOperation enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RichMenuBatchOperation {
    RichMenuBatchLinkOperation(Box<models::RichMenuBatchLinkOperation>),
    RichMenuBatchUnlinkOperation(Box<models::RichMenuBatchUnlinkOperation>),
    RichMenuBatchUnlinkAllOperation(Box<models::RichMenuBatchUnlinkAllOperation>),
}

impl Default for RichMenuBatchOperation {
    fn default() -> Self {
        Self::RichMenuBatchLinkOperation(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::RichMenuBatchLinkOperation> for RichMenuBatchOperation {
    fn from(value: models::RichMenuBatchLinkOperation) -> Self {
        RichMenuBatchOperation::RichMenuBatchLinkOperation(Box::new(value))
    }
}

impl From<models::RichMenuBatchUnlinkOperation> for RichMenuBatchOperation {
    fn from(value: models::RichMenuBatchUnlinkOperation) -> Self {
        RichMenuBatchOperation::RichMenuBatchUnlinkOperation(Box::new(value))
    }
}

impl From<models::RichMenuBatchUnlinkAllOperation> for RichMenuBatchOperation {
    fn from(value: models::RichMenuBatchUnlinkAllOperation) -> Self {
        RichMenuBatchOperation::RichMenuBatchUnlinkAllOperation(Box::new(value))
    }
}
