/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums-v2.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubstitutionObject enum using newtype pattern (wraps structs in Box)
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubstitutionObject {
    MentionSubstitutionObject(Box<models::MentionSubstitutionObject>),
    EmojiSubstitutionObject(Box<models::EmojiSubstitutionObject>),
}

impl Default for SubstitutionObject {
    fn default() -> Self {
        Self::MentionSubstitutionObject(Box::new(Default::default()))
    }
}

// Conversion methods from struct types to enum variants
impl From<models::MentionSubstitutionObject> for SubstitutionObject {
    fn from(value: models::MentionSubstitutionObject) -> Self {
        SubstitutionObject::MentionSubstitutionObject(Box::new(value))
    }
}

impl From<models::EmojiSubstitutionObject> for SubstitutionObject {
    fn from(value: models::EmojiSubstitutionObject) -> Self {
        SubstitutionObject::EmojiSubstitutionObject(Box::new(value))
    }
}
