/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubstitutionObject enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SubstitutionObject {
    #[serde(rename = "mention")]
    MentionSubstitutionObject {
        #[serde(rename = "mentionee")]
        mentionee: Box<models::MentionTarget>,
    },
    #[serde(rename = "emoji")]
    EmojiSubstitutionObject {
        #[serde(rename = "productId")]
        product_id: String,
        #[serde(rename = "emojiId")]
        emoji_id: String,
    },
}

impl Default for SubstitutionObject {
    fn default() -> Self {
        // Using the first variant as default
        Self::MentionSubstitutionObject {
            mentionee: Box::new(Default::default()),
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::MentionSubstitutionObject> for SubstitutionObject {
    fn from(value: models::MentionSubstitutionObject) -> Self {
        SubstitutionObject::MentionSubstitutionObject {
            mentionee: value.mentionee,
        }
    }
}

impl From<models::EmojiSubstitutionObject> for SubstitutionObject {
    fn from(value: models::EmojiSubstitutionObject) -> Self {
        SubstitutionObject::EmojiSubstitutionObject {
            product_id: value.product_id,
            emoji_id: value.emoji_id,
        }
    }
}
