/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 * Post-processed by: post-process-enums.js
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Template enum with all fields inline for each variant
/// This is automatically generated from discriminated schemas
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Template {
    #[serde(rename = "buttons")]
    ButtonsTemplate {
        #[serde(rename = "thumbnailImageUrl", skip_serializing_if = "Option::is_none")]
        thumbnail_image_url: Option<String>,
        #[serde(rename = "imageAspectRatio", skip_serializing_if = "Option::is_none")]
        image_aspect_ratio: Option<String>,
        #[serde(rename = "imageSize", skip_serializing_if = "Option::is_none")]
        image_size: Option<String>,
        #[serde(
            rename = "imageBackgroundColor",
            skip_serializing_if = "Option::is_none"
        )]
        image_background_color: Option<String>,
        #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        #[serde(rename = "text")]
        text: String,
        #[serde(rename = "defaultAction", skip_serializing_if = "Option::is_none")]
        default_action: Option<Box<models::Action>>,
        #[serde(rename = "actions")]
        actions: Vec<models::Action>,
    },
    #[serde(rename = "confirm")]
    ConfirmTemplate {
        #[serde(rename = "text")]
        text: String,
        #[serde(rename = "actions")]
        actions: Vec<models::Action>,
    },
    #[serde(rename = "carousel")]
    CarouselTemplate {
        #[serde(rename = "columns")]
        columns: Vec<models::CarouselColumn>,
        #[serde(rename = "imageAspectRatio", skip_serializing_if = "Option::is_none")]
        image_aspect_ratio: Option<String>,
        #[serde(rename = "imageSize", skip_serializing_if = "Option::is_none")]
        image_size: Option<String>,
    },
    #[serde(rename = "image_carousel")]
    ImageCarouselTemplate {
        #[serde(rename = "columns")]
        columns: Vec<models::ImageCarouselColumn>,
    },
}

impl Default for Template {
    fn default() -> Self {
        // Using the first variant as default
        Self::ButtonsTemplate {
            thumbnail_image_url: None,
            image_aspect_ratio: None,
            image_size: None,
            image_background_color: None,
            title: None,
            text: String::new(),
            default_action: None,
            actions: Vec::new(),
        }
    }
}

// Conversion methods from struct types to enum variants
impl From<models::ButtonsTemplate> for Template {
    fn from(value: models::ButtonsTemplate) -> Self {
        Template::ButtonsTemplate {
            thumbnail_image_url: value.thumbnail_image_url,
            image_aspect_ratio: value.image_aspect_ratio,
            image_size: value.image_size,
            image_background_color: value.image_background_color,
            title: value.title,
            text: value.text,
            default_action: value.default_action,
            actions: value.actions,
        }
    }
}

impl From<models::ConfirmTemplate> for Template {
    fn from(value: models::ConfirmTemplate) -> Self {
        Template::ConfirmTemplate {
            text: value.text,
            actions: value.actions,
        }
    }
}

impl From<models::CarouselTemplate> for Template {
    fn from(value: models::CarouselTemplate) -> Self {
        Template::CarouselTemplate {
            columns: value.columns,
            image_aspect_ratio: value.image_aspect_ratio,
            image_size: value.image_size,
        }
    }
}

impl From<models::ImageCarouselTemplate> for Template {
    fn from(value: models::ImageCarouselTemplate) -> Self {
        Template::ImageCarouselTemplate {
            columns: value.columns,
        }
    }
}
