/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Template {
    #[serde(rename="buttons")]
    ButtonsTemplate {
    },
    #[serde(rename="carousel")]
    CarouselTemplate {
    },
    #[serde(rename="confirm")]
    ConfirmTemplate {
    },
    #[serde(rename="image_carousel")]
    ImageCarouselTemplate {
    },
}

impl Default for Template {
    fn default() -> Self {
        Self::ButtonsTemplate {
        }
        
    }
}


