/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UriImagemapAction {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "area", skip_serializing_if = "Option::is_none")]
    pub area: Option<Box<models::ImagemapArea>>,
    #[serde(rename = "linkUri")]
    pub link_uri: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl UriImagemapAction {
    pub fn new(link_uri: String) -> UriImagemapAction {
        UriImagemapAction {
            r#type: None,
            area: None,
            link_uri,
            label: None,
        }
    }
}

