/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`acquire_chat_control`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AcquireChatControlError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`detach_module`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DetachModuleError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_modules`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetModulesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`release_chat_control`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReleaseChatControlError {
    UnknownValue(serde_json::Value),
}


/// If the Standby Channel wants to take the initiative (Chat Control), it calls the Acquire Control API. The channel that was previously an Active Channel will automatically switch to a Standby Channel. 
pub async fn acquire_chat_control(configuration: &configuration::Configuration, chat_id: &str, acquire_chat_control_request: Option<models::AcquireChatControlRequest>) -> Result<(), Error<AcquireChatControlError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_chat_id = chat_id;
    let p_body_acquire_chat_control_request = acquire_chat_control_request;

    let uri_str = format!("{}/v2/bot/chat/{chatId}/control/acquire", configuration.base_path, chatId=crate::apis::urlencode(p_path_chat_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_acquire_chat_control_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AcquireChatControlError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// The module channel admin calls the Detach API to detach the module channel from a LINE Official Account.
pub async fn detach_module(configuration: &configuration::Configuration, detach_module_request: Option<models::DetachModuleRequest>) -> Result<(), Error<DetachModuleError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_detach_module_request = detach_module_request;

    let uri_str = format!("{}/v2/bot/channel/detach", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_detach_module_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DetachModuleError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets a list of basic information about the bots of multiple LINE Official Accounts that have attached module channels.
pub async fn get_modules(configuration: &configuration::Configuration, start: Option<&str>, limit: Option<i32>) -> Result<models::GetModulesResponse, Error<GetModulesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_start = start;
    let p_query_limit = limit;

    let uri_str = format!("{}/v2/bot/list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start {
        req_builder = req_builder.query(&[("start", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetModulesResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetModulesResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetModulesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// To return the initiative (Chat Control) of Active Channel to Primary Channel, call the Release Control API. 
pub async fn release_chat_control(configuration: &configuration::Configuration, chat_id: &str) -> Result<(), Error<ReleaseChatControlError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_chat_id = chat_id;

    let uri_str = format!("{}/v2/bot/chat/{chatId}/control/release", configuration.base_path, chatId=crate::apis::urlencode(p_path_chat_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ReleaseChatControlError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

