/*
 * LINE Messaging API
 *
 * This document describes LINE Messaging API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use tokio::fs::File as TokioFile;
use tokio_util::codec::{BytesCodec, FramedRead};

/// struct for typed errors of method [`get_message_content`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMessageContentError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_message_content_preview`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMessageContentPreviewError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_message_content_transcoding_by_message_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMessageContentTranscodingByMessageIdError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_rich_menu_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRichMenuImageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_rich_menu_image`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetRichMenuImageError {
    UnknownValue(serde_json::Value),
}

/// Download image, video, and audio data sent from users.
pub async fn get_message_content(
    configuration: &configuration::Configuration,
    message_id: &str,
) -> Result<reqwest::Response, Error<GetMessageContentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_message_id = message_id;

    let uri_str = format!(
        "{}/v2/bot/message/{messageId}/content",
        configuration.base_path,
        messageId = crate::apis::urlencode(p_path_message_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetMessageContentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Get a preview image of the image or video
pub async fn get_message_content_preview(
    configuration: &configuration::Configuration,
    message_id: &str,
) -> Result<reqwest::Response, Error<GetMessageContentPreviewError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_message_id = message_id;

    let uri_str = format!(
        "{}/v2/bot/message/{messageId}/content/preview",
        configuration.base_path,
        messageId = crate::apis::urlencode(p_path_message_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetMessageContentPreviewError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Verify the preparation status of a video or audio for getting
pub async fn get_message_content_transcoding_by_message_id(
    configuration: &configuration::Configuration,
    message_id: &str,
) -> Result<
    models::GetMessageContentTranscodingResponse,
    Error<GetMessageContentTranscodingByMessageIdError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_message_id = message_id;

    let uri_str = format!(
        "{}/v2/bot/message/{messageId}/content/transcoding",
        configuration.base_path,
        messageId = crate::apis::urlencode(p_path_message_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetMessageContentTranscodingResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetMessageContentTranscodingResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetMessageContentTranscodingByMessageIdError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Download rich menu image.
pub async fn get_rich_menu_image(
    configuration: &configuration::Configuration,
    rich_menu_id: &str,
) -> Result<reqwest::Response, Error<GetRichMenuImageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_rich_menu_id = rich_menu_id;

    let uri_str = format!(
        "{}/v2/bot/richmenu/{richMenuId}/content",
        configuration.base_path,
        richMenuId = crate::apis::urlencode(p_path_rich_menu_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRichMenuImageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Upload rich menu image
pub async fn set_rich_menu_image(
    configuration: &configuration::Configuration,
    rich_menu_id: &str,
    body: Option<std::path::PathBuf>,
) -> Result<(), Error<SetRichMenuImageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_rich_menu_id = rich_menu_id;
    let p_body_body = body;

    let uri_str = format!(
        "{}/v2/bot/richmenu/{richMenuId}/content",
        configuration.base_path,
        richMenuId = crate::apis::urlencode(p_path_rich_menu_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    if let Some(param_value) = p_body_body {
        let file = TokioFile::open(param_value).await?;
        let stream = FramedRead::new(file, BytesCodec::new());
        req_builder = req_builder.body(reqwest::Body::wrap_stream(stream));
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SetRichMenuImageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
